# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-04 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NotesDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emailID', models.CharField(max_length=100)),
                ('videoID', models.CharField(max_length=50)),
                ('startTime', models.CharField(max_length=10)),
                ('endTime', models.CharField(max_length=10)),
                ('notes', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='notesdb',
            unique_together=set([('emailID', 'videoID', 'startTime')]),
        ),
    ]
